### ISSUE TITLE
Grafkalender

### ISSUE THREAD

**Issue by hedintobias** [Pyroarti/Csv-visualizer#1]
![image](https://user-images.githubusercontent.com/113300001/230063310-a88c384c-dd3c-4a00-a0c1-f1516ec51629.png)
Går inte välja samma datum och korrekt datum som csv-filen innehåller

**Comment by hedintobias** [comment]
Går inte att skriva de datumen också

**Comment by Pyroarti** [comment]
Fixed the problem with the calendar now properly showing which dates the data is.
