### ISSUE TITLE
Exit hänger sig samt progammet verkar inte stänga av sig helt

### ISSUE THREAD

**Issue by hedintobias** [Pyroarti/Csv-visualizer#3]
Knappen "Exit" fungerar inte och programmet hamnar i "Not Responding". Och även om man stänger med kryss i hörnet så verkar inte programmet bli avstängt då det inte går att starta igen.

**Comment by hedintobias** [comment]
Det hänger något på att Webservern är startad och inte stängs av. Så får du bara den avstängd så stänger nog sig programmet

**Comment by Pyroarti** [comment]
Fixed the problem with the exit button now working properly.
